services:
  redis-docker:
    container_name: redis-docker
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master