services:
  nginx-reverse-proxy:
    image: nginx:bookworm
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf.d/site.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl