apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: hoen-cluster
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9100
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: nginx
          bootstrap:
            host: bootstrap.kafka.rke2-queen
          brokers:
            - broker: 0
              host: broker-0.kafka.rke2-queen
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: 3.8
    storage:
      type: ephemeral
    authorization:
      type: simple
      superUsers:
        - CN=professor-birch
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
