apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: hoen-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

      - name: dev0forward
        port: 9192
        type: nodeport
        tls: false

      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls

      - name: external
        port: 9100
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: nginx
          bootstrap:
            host: bootstrap.kafka.rke2-queen
          brokers:
            - broker: 0
              host: broker-0.kafka.rke2-queen
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: 3.8
    storage:
      type: ephemeral
    # authorization:
    #   type: simple
    #   superUsers:
    #     - CN=professor-birch
  entityOperator:
    topicOperator:
      resources:
        limits:
          memory: 256Mi
    userOperator:
      resources:
        limits:
          memory: 256Mi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: hoen-cluster
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
  resources:
    limits:
      memory: 512Mi
      cpu: "2"