apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: professor-birch
  labels:
    strimzi.io/cluster: hoen-cluster
spec:
  authentication:
    type: tls
  # authorization:
  #   type: simple
  #   acls:
  #     - resource:
  #         type: topic
  #         name: "*"
  #         patternType: literal
  #       operation: All
  #       host: "*"
  #     - resource:
  #         type: group
  #         name: "*"
  #         patternType: literal
  #       operation: All
  #       host: "*"