version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    volumes: 
      - ./docker/master-zookeeper-data:/var/lib/zookeeper/data
      - ./docker/master-zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - kafka-network

  broker:
    container_name: broker-alpha
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties \
          --override replica.fetch.max.bytes=52428800 \
          --override message.max.bytes=52428800 \
          --override listeners=$${KAFKA_LISTENERS} \
          --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} \
          --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} \
          --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} \
          --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9095:9095"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094,DOCKER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,OUTSIDE://localhost:9094,DOCKER://host.docker.internal:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes: 
      - ./docker/kafka-broker-alpha/data:/var/lib/kafka/data
      - ./docker/kafka-broker-alpha/logs:/tmp/logs # Problemas de permisos al arrancar el contenedor para generar el archivo de log
    networks:
      - kafka-network

networks:
  kafka-network: