version: '3.1'

services:
  irc-server:
    image: inspircd/inspircd-docker:3
    ports:
      - 6667:6667 # clients, plaintext
      - 6697:6697 # clients, TLS
      - 7000:7000 # server, plaintext
      - 7001:7001 #	server, TLS
    environment:
      - INSP_NET_SUFFIX=${INSP_NET_SUFFIX:-example.com}
      - INSP_NET_NAME=${INSP_NET_NAME:-omega}
      - INSP_ADMIN_NAME=${INSP_ADMIN_NAME:-Jonny English}
      - INSP_ADMIN_NICK=${INSP_ADMIN_NICK:-MI5}
      - INSP_ADMIN_EMAIL=${INSP_ADMIN_EMAIL:-jonny.english@example.com}